---
title: Lifebrain Global Brain Health Survey
authors:
  - name: Athanasia M. Mowinckel
    department: Center for Lifespan Changes in Brain and Cognition, Dept. of Psychology
    affiliation: University of Oslo
    location: Oslo, Norway
    email: a.m.mowinckel@psykologi.uio.no
output: 
  pdf_document:
    toc: true
    number_sections: true
graphics: yes
bibliography: references.bib
link-citations: true
---

```{r setup, include = FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
pkgconfig::set_config("tibble::rownames" = NA) 

opts_chunk$set(
  echo = FALSE, 
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.retina = 3,
  fig.width = 8,
  out.width = "100%"
)
options(knitr.kable.NA = '')
set.seed(4455)
source(here::here('R/utils.R'))
source(here::here('scripts/data-utils.R'))
source(here::here('scripts/model-utils.R'))
source(here::here('scripts/ggplot-utils.R'))
```


```{r q5-results, results = "asis"}
load(here::here("data/q5_long.Rda"))
child_env <- new.env()
child_env$data <- q5
child_env$q <- "Q5"
child_env$wanted_formula <- wanted_formula
child_env$table_title <- function(x) sprintf("\n## How often do I _%s_ \n", x)

res <- knit_child(
  here::here("docs/child_docs/ord_mod.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')

```

```{r q6-results, results = "asis"}
load(here::here("data/q6_long.Rda"))
child_env <- new.env()
child_env$data <- q6
child_env$q <- "Q6"
child_env$wanted_formula <- wanted_formula
child_env$table_title <- function(x) sprintf("\n## I _%s_ purposefully for my brain health.\n", x)
res <- knit_child(
  here::here("docs/child_docs/ord_mod.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')

```

```{r q11-results, results = "asis"}
load(here::here("data/q11_long.Rda"))
child_env <- new.env()
child_env$data <- q11
child_env$q <- "Q11"
child_env$wanted_formula <- wanted_formula
child_env$table_title <- function(x) sprintf("\n## How likely I am to _%s_ to reduce the risk of brain disease.\n", x)

res <- knit_child(
  here::here("docs/child_docs/ord_mod.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')

```

```{r q12-results, results = "asis"}
load(here::here("data/q12_long.Rda"))
child_env <- new.env()
child_env$data <- q12
child_env$q <- "Q12"
child_env$wanted_formula <- wanted_formula
child_env$table_title <- function(x) sprintf("\n## _%s_ would motive me to change my lifestyle to improive brain health.\n", gsub("\\n", " ", x))

res <- knit_child(
  here::here("docs/child_docs/bin_mod.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')

```

```{r q13-results, results = "asis"}
load(here::here("data/q13_long.Rda"))
child_env <- new.env()
child_env$data <- q13
child_env$q <- "Q13"
child_env$wanted_formula <- wanted_formula
child_env$table_title <- function(x) sprintf("\n## _%s_ would prevent my from changing my lifestyle to improve brain health.\n", gsub("\\n", " ", x))

res <- knit_child(
  here::here("docs/child_docs/bin_mod.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')

```

```{r, include=FALSE}
models <- list.files(here::here("docs/paper3/supplementary"), pattern = "^Q", full.names = TRUE)
models_dt <- lapply(models, function(x){
  sheets <- openxlsx::getSheetNames(x)
  sh <- lapply(sheets, function(z){
    openxlsx::read.xlsx(x, z)
  })
  names(sh) <- paste(tolower(gsub("_mod_tables\\.xlsx", "", basename(x))), sheets, sep="_")
  sh
})
models_dt <- unlist(models_dt, recursive = FALSE)
openxlsx::write.xlsx(models_dt, file = here::here("docs/paper3/si_all_models.xlsx"))
```

