---
output: pdf_document
---
```{r, include=FALSE}
data <- gbhs_long_q(q , data)
l <- length(unique(data$key))
base_fig_height <- 3
if(l > base_fig_height)
  base_fig_height <- l/2
```

# Question `r q`

## Overall


```{r , fig.height=base_fig_height}
data |> 
  ggstacked( 
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white"),
    n_breaks = 5,
  ) +
  labs(x="", y="", fill = "Response",
       title = title) +
  theme(legend.position = "right") +
  scale_fill_discrete() +
  coord_cartesian(xlim = c(0, 1.1), clip = "off") +
  NULL
```

## Gender

```{r , fig.height=base_fig_height+1}
data |> 
  ggstacked_wrap(
    fct_rev(sex),
    sort_key = FALSE,
    npos = 1.15, 
    min_pc = .2,
    text_size = 2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(clip = "off") &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by gender",
    caption = str_wrap(glue("{descr} Here divided by respondent gender. Categories with less than 20% of the responses do not have percentages shown. Subplots are ordereded by total rated importance across all groups.  The number of male and female respondents differ between subplots due to missing answers."), params$chr_width)
  )
```


## Age groups
```{r , fig.height=base_fig_height+2}
data |> 
  ggstacked_wrap(
    age,
    sort_key = FALSE,
    npos = 1.25, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by age groups",
    caption = str_wrap(glue("{descr} Here divided by respondent age group. Categories with less than 20% of the responses do not have percentages shown. Subplots are ordered by total rated importance across all groups"), params$chr_width)
  )
```

## Education

```{r , fig.height=base_fig_height+2}
data |> 
  ggstacked_wrap(
    fct_rev(education),
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=6)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by educational level",
    caption = str_wrap(glue("{descr} Here divided by respondent self-reported education level. Categories with less than 20% of the responses do not have percentages shown. Subplots are ordered by total rated importance across all groups"), params$chr_width)
  )
```

## Country

```{r , fig.height=base_fig_height*1.8, eval = include_country}
data |> 
  ggstacked_wrap(
    fct_rev(region),
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by country of residence",
    caption = str_wrap(glue("{descr} Here divided by respondent self-reported country of residence, showing the {params$country_n} with the most responses while all other countries are represented in 'Other'. Categories with less than 20% of the responses do not have percentages shown. Subplots are ordered by total rated importance across all groups"), params$chr_width)
  )
```

## Health experience/education

```{r , fig.height=base_fig_height+2}
data |> 
  ggstacked_wrap(
    q24_exp_health_care,
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "By reported education or work experience in health care",
    caption = str_wrap(glue("{descr} Here divided by having education or work experience in health care. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )
```


## Cognitive health 

```{r , fig.height=base_fig_height+2}
data |> 
  ggstacked_wrap(
    fct_rev(q25_cognitive_health),
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by self-reported rating of cognitive health",
    caption = str_wrap(glue("{descr} Here divided by self-reported rating of cognitive health. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )

```

## Mental health

```{r , fig.height=base_fig_height+2}
data |> 
  ggstacked_wrap(
    fct_rev(q26_emotional_health),
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by self-reported rating of mental health",
    caption = str_wrap(glue("{descr} Here divided by self-reported rating of mental health. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )

```

## Illness

```{r , fig.height=base_fig_height+1}
data |> 
  ggstacked_wrap(
    q27_illness,
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  )  &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by experience of long-standing illness, disability, or health problem",
    caption = str_wrap(glue("{descr} Here divided whether they had experience with long-standing illness, disability, or health problem. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )
```

## Brain disease care

```{r , fig.height=base_fig_height+1}
data |> 
  ggstacked_wrap(
    q28_brain_disease_care,
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  ) &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "by experience of taking care of family member with brain disease",
    caption = str_wrap(glue("{descr} Here divided whether they had experience with looking after a member of family with brain disease. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )
```

## Research participation

```{r , fig.height=base_fig_height+1}
data |> 
  ggstacked_wrap(
    q17_brain_research_part,
    sort_key = FALSE,
    npos = 1.3, 
    min_pc = .2,
    size = 1.5,
    lab = ifelse(!grepl(pattern, value), pc, NA),
    col = ifelse(!grepl(pattern, value), "black", "white")
  )  &
  coord_cartesian(xlim = c(0, 1.4), clip = "off") &
  theme(axis.text.y = element_text(size=7)) &
  scale_fill_discrete() &
  plot_annotation(
    title = title,
    subtitle = "By experience of brain research participation",
    caption = str_wrap(glue("{descr} Here divided whether they have participated in brain research projects. Categories with less than 20% of the responses do not have percentages shown."), params$chr_width)
  )
```
