---
title: Lifebrain Global Brain Health Survey
authors:
  - name: Athanasia M. Mowinckel
    department: Center for Lifespan Changes in Brain and Cognition, Dept. of Psychology
    affiliation: University of Oslo
    location: Oslo, Norway
    email: a.m.mowinckel@psykologi.uio.no
output: 
  pdf_document:
    toc: true
    number_sections: true
    includes:
      header-includes: 
        - \pgenumbering{gobble}
graphics: yes
bibliography: references.bib
link-citations: true
params:
  comparison: FALSE
---

```{r setup, include = FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(furrr)
pkgconfig::set_config("tibble::rownames" = NA) 

opts_chunk$set(
  echo = FALSE, 
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.retina = 3,
  fig.width = 8,
  out.width = "100%"
)
options(knitr.kable.NA = '')
set.seed(4455)
source(here::here('R/model-utils'))

modeltable <- function(data, formula) {
  
  models <- data %>% 
    nest_by(key) %>% 
    mutate(
      bin_mod = list(glm(formula, 
                         family = binomial(link = "logit"), 
                         data = data)),
      bin_tidy =  list(tidy(bin_mod)),
      bin_table = list(bin_tidy %>% 
                         rename(OR = estimate,
                                p = p.value) %>% 
                         mutate(
                           p = p.adjust(p, "fdr", 120),
                           p = case_when(
                             p >  0.05  ~ sprintf("%s",  format(p, digits = 2)),
                             p <  0.001 ~ sprintf("%s**", format(p, digits = 3)),
                             p <= 0.05  ~ sprintf("%s*", format(p, digits = 2)),
                             TRUE       ~ NA_character_),
                           ci = std.error * 2.58, 
                           lower = OR - ci, 
                           upper = OR + ci,
                         ) )
    )
  
  models %>% 
    unnest(bin_table) %>% 
    select(-ci, -starts_with("bin"), -data) %>% 
    rename(model = key) %>% 
    kable(digits = 2, booktabs = TRUE, longtable = TRUE) %>% 
    kable_styling() %>% 
    collapse_rows(1)
  
}
```

# Question 1
```{r q2-results, results='asis'}
load(here::here("data/q2_long.rda"))
q2_data <- fix_data(q2_data)
mod <- binary ~ 1 + gender + age + education
q2_data$data %>% 
  modeltable(mod)
```
The general tendencies as before remain.

# Question 2

```{r q3-data, results='asis'}
load(here::here("data/q3_long.rda"))
q3_data <- fix_data(q3_data)
mod <- binary ~ 1 + gender + age + education
q3_data$data %>% 
  filter(key == c("Middle age", "Old age")) %>% 
  modeltable(mod)
```
Men still consider middle and old age as less important when controlling for age and education.

# Question 3

```{r q4-data, results='asis'}
load(here::here("data/q4_long.rda"))
q4_data <- fix_data(q4_data)
mod <- binary ~ 1 + relationship + age + education
q4_data$data %>% 
  filter(key == "Alzheimer's") %>% 
  modeltable(mod)
```
The association did not hold when controlling for age and education level.