---
params: 
  country: "all"
  country_n: 7
  chr_width: 135
  data: gbhs::gbhs
title: Lifebrain Global Brain Health Survey
subtitle: "for country: `r params$country`"
authors:
  - name: Athanasia M. Mowinckel
    department: Center for Lifespan Changes in Brain and Cognition, Dept. of Psychology
    affiliation: University of Oslo
    location: Oslo, Norway
    email: a.m.mowinckel@psykologi.uio.no
output: 
  pdf_document:
    toc: true
    number_sections: true
    keep_tex:  false
graphics: yes
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.retina = 3,
                      fig.width = 8,
                      fig.pos = "H",
                      out.width = "100%")
options(knitr.kable.NA = '-')

library(patchwork)
library(knitr)
library(kableExtra)
library(tidyverse) 
library(glue)
library(gbhs)

source(gbhs_path_utilities("data-utils.R"))
theme_set(theme_classic() + theme(legend.position = "bottom"))
min_resp_keep = .3
chr_width <- 100
```

```{r data, include=FALSE}
data <- get_data(params$data)

include_country = TRUE
if(params$country != "all"){
  data <- filter(data, q19_residence == params$country) |> 
    mutate(
      region = fct_lump(q19_residence, params$country_n, 
                        other_level = "Other", 
                        ties.method = "min"),
      region = ifelse(q19_residence == params$country, 
                      params$country, 
                      as.character(region)),
      region = fct_infreq(region),
      region = fct_relevel(region, "Other", after = Inf)
    )
  # include_country = FALSE
}else{
  data <- data |> 
    mutate(
      region = fct_lump(q19_residence, params$country_n, 
                        other_level = "Other", 
                        ties.method = "min"),
      region = fct_infreq(region),
      region = fct_relevel(region, "Other", after = Inf)
    )
  
  data_sum <- data |>
    group_by(region) |>
    tally() |> 
    ungroup() |> 
    rbind(data.frame(region = "Total", n = nrow(data)))
}

response_rates <- data |> 
  gather(name, value, -submission_id) |> 
  group_by(submission_id) |> 
  summarise(nas = sum(is.na(value)),
            n_qs = length(value),
            pc = nas/n_qs) |> 
  arrange(desc(nas))


pc_female <- data |> 
  group_by(q20_sex) |> 
  tally() |> 
  mutate(pc = percent(pc(n)))


tab <- data |> 
  select(language, ends_with("Spec")) |> 
  pivot_longer(ends_with("Spec"),  values_drop_na = TRUE) |> 
  group_by(name, language) |> 
  tally() 

tab |> 
  pivot_wider(names_from = language,
              values_from = n)

tab |> 
  ggplot(aes(x = language, y = n)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = thousand(n)), 
            size = 2, hjust = 0) +
  facet_wrap(~name, scales = "free") +
  coord_flip()
```

```{r}
mutate(data, 
       country = case_when(
         q19_residence == "UK" ~ "United Kingdom",
         q19_residence == "USA" ~ "United States",
         q19_residence  == "Slovakia" ~ "Slovak Republic",
         TRUE ~ q19_residence 
       )
)|> 
  left_join(
    gapminder::gapminder |> 
      select(country, continent) |> 
      distinct(),
    by = "country"
  ) |> 
  select(country, continent) |> 
  mutate(
    continent = case_when(
      !is.na(continent)       ~ as.character(continent),
      country == "Cyprus"     ~ "Europe",
      country == "Azerbaijan" ~ "Europe",
      country == "Ukraine"    ~ "Europe",
      country == "Estonia"    ~ "Europe",
      country == "Luxembourg" ~ "Europe",
      country == "Belarus"    ~ "Europe",
      country == "Lithuania"  ~ "Europe",
      country == "San Marino" ~ "Europe",
      country == "Lithuania"  ~ "Europe",
      country == "Malta"      ~ "Europe",
      country == "Andorra"    ~ "Europe",
      country == "Uzbekistan" ~ "Asia",
      country == "Fiji"       ~ "Oceania",
      country == "Suriname"   ~ "Americas",
      country == "Zaire"      ~ "Africa",
      country == "United Arab Emirates"    ~ "Asia"
    )
  ) |> 
  group_by(continent, country) |> 
  tally() |> 
  summarise(
    n = sum(n),
    n_country = length(country)
  ) |> 
  mutate(tot_country = sum(n_country)) |> 
  kable(booktabs = TRUE) |> 
  kable_styling()
```

\newpage

```{r q2-results, results = "asis"}
child_env <- new.env()
child_env$params <- params
child_env$data <- data
child_env$q <- 2
child_env$title   <- "Factors considered to influence brain health"
child_env$pattern <- "No|Mod|We"
child_env$descr <- "Question 1 asked respondents to rate on a 5-level likert-scale how strongly different life periods influence brain health."

res <- knit_child(
  gbhs_path_child("ord_desc.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')
```

\newpage

```{r q3-results, results = "asis"}
child_env <- new.env()
child_env$params <- params
child_env$data <- data
child_env$q <- 3
child_env$title   <- "Life periods to look after ones’ brain"
child_env$pattern <- "Mod|Not"
child_env$descr <- "Question 2 asked respondents to rate on a 4−level scale at which life stages it is important to look after one's  brain health. In the womb (before birth); Childhood (0-12 years); Adolescence (13-18 years); Young adulthood (19−45 years); Middle age (45-65 years); Old age (over 65 years)"

res <- knit_child(
  gbhs_path_child("ord_desc.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')
```

\newpage


```{r q4-results, results = "asis"}
child_env <- new.env()
child_env$params <- params
child_env$data <- data
child_env$q <- 4
child_env$title <- "Diseases/disorders associated with the brain"
child_env$descr <- glue::glue("Respondents were given the option to tick boxes with the diseases presented above to indicate which ones they associated with the brain. They were allowed to select as many categories as they wished. The question was optional, and as such we present data from the {thousand(length(unique(gbhs_long_q(4, data)$submission_id)))} who responded to the question. We do not know if those who refrained from responding did so because they did not associate any of the diseases with the brain, or if they simply did not wish to respond.")

res <- knit_child(
  gbhs_path_child("bin_desc.Rmd"),
  envir = child_env,
  quiet = TRUE
)
cat(res, sep = '\n')
```
